import Link from "next/link";
import { ArrowRight, Check, HardHat, ShieldCheck, Target, Workflow } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import ImageLightbox from "@/components/ImageLightbox";
import ContactForm from "@/components/ContactForm";
import { projects, services } from "@/data/site";

const strengths: { icon: LucideIcon; title: string; description: string }[] = [
  { icon: Target, title: "Expertise technique", description: "Des solutions adaptées aux contraintes réelles du terrain." },
  { icon: Workflow, title: "Respect des engagements", description: "Une planification et un suivi clair des étapes." },
  { icon: ShieldCheck, title: "HSE & prévention", description: "Une attention constante aux risques, aux personnes et au site." },
  { icon: HardHat, title: "Vision intégrée", description: "Études, travaux et approvisionnement dans une logique cohérente." },
];

export default function Home() { return <main>
  <section className="bg-off py-10 lg:py-14"><div className="site-container grid min-h-[660px] items-center gap-12 lg:grid-cols-[1.02fr_.98fr] lg:gap-16"><div><span className="eyebrow">Partenaire technique & opérationnel</span><h1 className="display max-w-3xl font-extrabold text-navy">Construire, connecter et <span className="text-brand">équiper durablement.</span></h1><p className="lead mt-6 max-w-2xl">SD International Group accompagne entreprises, institutions et collectivités dans leurs projets de BTP, génie civil, énergie, réseaux électriques HT/MT/BT, études, environnement, import-export et logistique.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn btn-primary" href="/contact">Contacter l’entreprise <ArrowRight size={18}/></Link><a className="btn btn-outline" href="#services">Découvrir nos expertises</a></div></div><div className="relative pb-8 pl-0 md:pl-10"><ImageLightbox src="https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1400&q=85" alt="Professionnels sur un chantier de construction" priority className="h-[500px] rounded-lg shadow-soft lg:h-[590px]" sizes="(min-width:1024px) 48vw, 100vw"/><div className="absolute bottom-0 left-0 max-w-[290px] rounded-lg border bg-white p-5 shadow-soft"><strong className="block text-navy">Une approche pluridisciplinaire</strong><span className="mt-1 block text-sm text-muted">De l’étude à l’exécution et à l’approvisionnement.</span></div></div></div></section>
  <div className="site-container grid bg-navy px-5 py-7 text-white md:grid-cols-4 md:px-7">{["BTP & génie civil", "Énergie & réseaux", "Études & environnement", "Négoce & logistique"].map((x,i)=><div key={x} className="border-white/15 px-4 py-3 text-sm font-bold md:border-r md:last:border-0"><span className="mr-2 text-gold">0{i+1}</span>{x}</div>)}</div>
  <section id="a-propos" className="section scroll-mt-24"><div className="site-container grid items-center gap-14 lg:grid-cols-2 lg:gap-20"><ImageLightbox src="https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1400&q=85" alt="Équipe technique réunie sur un chantier" className="h-[480px] rounded-lg shadow-soft md:h-[570px]" sizes="(min-width:1024px) 50vw, 100vw"/><div><span className="eyebrow">À propos</span><h2 className="heading font-extrabold text-navy">Une expertise mobilisée autour de vos enjeux.</h2><p className="lead mt-6">SD International Group développe une approche intégrée pour répondre aux besoins d’infrastructures, d’énergie, d’études techniques et d’approvisionnement.</p><div className="mt-8 grid gap-5">{["Comprendre les contraintes opérationnelles de chaque projet.","Coordonner études, exécution et approvisionnement.","Placer la sécurité, la qualité et la durabilité au cœur des interventions."].map(x=><div key={x} className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-blue-50 text-brand"><Check size={16}/></span><span>{x}</span></div>)}</div></div></div></section>
  <section id="services" className="section scroll-mt-24 bg-off"><div className="site-container"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="eyebrow">Domaines d’expertise</span><h2 className="heading max-w-2xl font-extrabold text-navy">Des compétences complémentaires, un interlocuteur engagé.</h2></div><p className="lead max-w-lg">Une offre structurée pour identifier rapidement la réponse adaptée à votre besoin.</p></div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{services.map(s=><article key={s.slug} className="overflow-hidden rounded-lg border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-soft"><ImageLightbox src={s.image} alt={s.title} className="h-56" sizes="(min-width:1024px) 25vw, 50vw"/><div className="p-6"><span className="text-xs font-extrabold text-brand">{s.number} · {s.short}</span><h3 className="mt-3 text-xl font-extrabold text-navy">{s.title}</h3><p className="mt-3 text-sm leading-6 text-muted">{s.description}</p><Link href={`/services/${s.slug}`} className="mt-5 inline-flex items-center gap-2 font-bold text-navy">Découvrir <ArrowRight size={16}/></Link></div></article>)}</div></div></section>
  <section className="section"><div className="site-container grid gap-12 lg:grid-cols-[.82fr_1.18fr]"><div className="self-start rounded-lg bg-navy p-9 text-white lg:sticky lg:top-28"><span className="eyebrow !text-blue-300">Pourquoi SD International ?</span><h2 className="text-3xl font-extrabold">Le sérieux d’un partenaire, au-delà de la prestation.</h2><p className="mt-5 leading-7 text-slate-300">Chaque projet doit inspirer confiance avant, pendant et après l’exécution.</p><Link href="/contact" className="btn btn-primary mt-7">Échanger sur votre besoin</Link></div><div className="grid gap-5 sm:grid-cols-2">{strengths.map(({ icon: Icon, title, description })=><article key={title} className="rounded-lg border border-slate-200 p-7"><Icon className="text-brand"/><h3 className="mt-5 text-xl font-extrabold text-navy">{title}</h3><p className="mt-2 leading-7 text-muted">{description}</p></article>)}</div></div></section>
  <section className="section bg-navy text-white"><div className="site-container"><span className="eyebrow !text-blue-300">Réalisations</span><h2 className="heading max-w-3xl font-extrabold">Le terrain parle mieux que de longs discours.</h2><p className="mt-5 max-w-2xl text-slate-300">Cette sélection sera enrichie avec les photographies et données validées de SD International Group.</p><div className="mt-10 grid gap-5 lg:grid-cols-[1.25fr_.75fr]">{projects.map((p,i)=><article key={p.title} className={`relative overflow-hidden rounded-lg ${i===0 ? "min-h-[560px] lg:row-span-2" : "min-h-[270px]"}`}><ImageLightbox src={p.image} alt={p.title} className="absolute inset-0 h-full" sizes={i===0?"65vw":"35vw"}/><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/80 via-transparent"/><div className="pointer-events-none absolute inset-x-6 bottom-6"><span className="text-sm text-slate-200">{p.category} · {p.location}</span><h3 className="mt-1 text-xl font-extrabold">{p.title}</h3></div></article>)}</div><Link href="/realisations" className="btn btn-primary mt-8">Voir les réalisations</Link></div></section>
  <section className="section"><div className="site-container grid items-center gap-14 lg:grid-cols-2"><div><span className="eyebrow">Négoce & fournitures</span><h2 className="heading font-extrabold text-navy">Un appui d’approvisionnement pour vos besoins techniques.</h2><p className="lead mt-6">Matériels, équipements électriques, produits industriels et lubrifiants industriels et marins pour les besoins professionnels.</p>{["Lubrifiants industriels et marins","Équipements et matériels électriques","Import-export et coordination logistique"].map(x=><p key={x} className="mt-5 flex gap-3 font-bold"><Check className="text-brand"/>{x}</p>)}<Link href="/services/negoce-import-export" className="btn btn-primary mt-8">Découvrir cette expertise</Link></div><ImageLightbox src="https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1400&q=85" alt="Entrepôt de logistique et d’approvisionnement" className="h-[520px] rounded-lg shadow-soft" sizes="50vw"/></div></section>
  <section className="section bg-off"><div className="site-container grid overflow-hidden rounded-lg border bg-navy text-white lg:grid-cols-[.72fr_1.28fr]"><div className="p-8 lg:p-12"><span className="eyebrow !text-blue-300">Prise de contact</span><h2 className="text-3xl font-extrabold">Parlez-nous de votre projet.</h2><p className="mt-5 leading-7 text-slate-300">Présentez votre besoin. Notre équipe pourra vous répondre avec les premiers éléments utiles.</p></div><ContactForm /></div></section>
  </main>; }
