import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Check, HardHat, ShieldCheck, Target, Workflow } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import ImageLightbox from "@/components/ImageLightbox";
import ContactForm from "@/components/ContactForm";
import { projects, services } from "@/data/site";

const strengths: { icon: LucideIcon; title: string; description: string }[] = [
  { icon: Target, title: "Compréhension des besoins", description: "Des réponses construites autour des objectifs et contraintes de chaque organisation." },
  { icon: Workflow, title: "Respect des engagements", description: "Une planification et un suivi clair des étapes." },
  { icon: ShieldCheck, title: "HSE & prévention", description: "Une attention constante aux risques, aux personnes et au site." },
  { icon: HardHat, title: "Vision intégrée", description: "Conseil, réalisation, fourniture et coordination dans une logique cohérente." },
];

export default function Home() { return <main>
  <section className="bg-off py-10 lg:py-14"><div className="site-container grid min-h-[660px] items-center gap-12 lg:grid-cols-[1.02fr_.98fr] lg:gap-16"><div><span className="eyebrow">Un groupe, des solutions complémentaires</span><h1 className="display max-w-3xl font-extrabold text-navy">Transformer vos besoins en <span className="text-brand">solutions concrètes.</span></h1><p className="lead mt-6 max-w-2xl">SD International Group mobilise des compétences diversifiées pour accompagner les entreprises, institutions et collectivités, de la réflexion à la réalisation, jusqu’à la fourniture et à la coordination opérationnelle.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn btn-primary" href="/contact">Contacter l’entreprise <ArrowRight size={18}/></Link><a className="btn btn-outline" href="#services">Découvrir nos activités</a></div></div><div className="relative pb-8 pl-0 md:pl-10"><ImageLightbox src="/images/hero/equipe-ingenieurs-afrique.jpg" alt="Équipe d’ingénieurs africains réunie autour de plans techniques" priority className="h-[500px] rounded-lg shadow-soft lg:h-[590px]" sizes="(min-width:1024px) 48vw, 100vw"/><div className="absolute bottom-0 left-0 max-w-[300px] rounded-lg border bg-white p-5 shadow-soft"><strong className="block text-navy">Une approche transversale</strong><span className="mt-1 block text-sm text-muted">Comprendre, coordonner et concrétiser chaque besoin.</span></div></div></div></section>
  <div className="site-container grid bg-navy px-5 py-7 text-white md:grid-cols-4 md:px-7">{["Conseil & études", "Solutions & réalisation", "Commerce & fournitures", "Coordination & logistique"].map((x,i)=><div key={x} className="border-white/15 px-4 py-3 text-sm font-bold md:border-r md:last:border-0"><span className="mr-2 text-gold">0{i+1}</span>{x}</div>)}</div>
  <section id="a-propos" className="section scroll-mt-24"><div className="site-container grid items-center gap-14 lg:grid-cols-2 lg:gap-20"><div className="relative flex min-h-[480px] items-center justify-center overflow-hidden bg-off px-8 md:min-h-[570px]"><span className="absolute inset-y-0 left-0 w-2 bg-gold"/><Image src="/images/logo-sd-international-new.png" alt="SD International Group" width={560} height={373} sizes="(min-width:1024px) 50vw, 90vw" className="h-auto w-full max-w-[520px]" /></div><div><span className="eyebrow">À propos</span><h2 className="heading font-extrabold text-navy">Plusieurs savoir-faire réunis autour de vos enjeux.</h2><p className="lead mt-6">SD International Group développe une approche multisectorielle et mobilise les compétences adaptées à la nature de chaque mission, sans enfermer ses interventions dans un domaine unique.</p><div className="mt-8 grid gap-5">{["Comprendre les objectifs et les contraintes de chaque organisation.","Associer conseil, coordination, réalisation et approvisionnement.","Placer la fiabilité, la qualité et la durabilité au cœur des interventions."].map(x=><div key={x} className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-blue-50 text-brand"><Check size={16}/></span><span>{x}</span></div>)}</div></div></div></section>
  <section id="services" className="section scroll-mt-24 bg-off"><div className="site-container"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="eyebrow">Champs d’intervention</span><h2 className="heading max-w-2xl font-extrabold text-navy">Des compétences complémentaires, mobilisées selon vos besoins.</h2></div><p className="lead max-w-lg">Ces activités illustrent nos capacités actuelles et peuvent être combinées dans une réponse globale.</p></div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{services.map(s=><article key={s.slug} className="overflow-hidden rounded-lg border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-soft"><ImageLightbox src={s.image} alt={s.title} className="h-56" sizes="(min-width:1024px) 25vw, 50vw"/><div className="p-6"><span className="text-xs font-extrabold text-brand">{s.number} · {s.short}</span><h3 className="mt-3 text-xl font-extrabold text-navy">{s.title}</h3><p className="mt-3 text-sm leading-6 text-muted">{s.description}</p><Link href={`/services/${s.slug}`} className="mt-5 inline-flex items-center gap-2 font-bold text-navy">Découvrir <ArrowRight size={16}/></Link></div></article>)}</div></div></section>
  <section className="section"><div className="site-container grid gap-12 lg:grid-cols-[.82fr_1.18fr]"><div className="self-start rounded-lg bg-navy p-9 text-white lg:sticky lg:top-28"><span className="eyebrow !text-blue-300">Pourquoi SD International ?</span><h2 className="text-3xl font-extrabold">Le sérieux d’un partenaire, au-delà de la prestation.</h2><p className="mt-5 leading-7 text-slate-300">Chaque projet doit inspirer confiance avant, pendant et après l’exécution.</p><Link href="/contact" className="btn btn-primary mt-7">Échanger sur votre besoin</Link></div><div className="grid gap-5 sm:grid-cols-2">{strengths.map(({ icon: Icon, title, description })=><article key={title} className="rounded-lg border border-slate-200 p-7"><Icon className="text-brand"/><h3 className="mt-5 text-xl font-extrabold text-navy">{title}</h3><p className="mt-2 leading-7 text-muted">{description}</p></article>)}</div></div></section>
  {projects.length > 0 && <section className="section bg-navy text-white"><div className="site-container"><span className="eyebrow !text-blue-300">Réalisations</span><h2 className="heading max-w-3xl font-extrabold">Des interventions concrètes, conduites avec exigence.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{projects.slice(0,3).map(p=><article key={p.title} className="overflow-hidden rounded-lg bg-[#102a43]"><ImageLightbox src={p.image} alt={p.title} className="h-64" sizes="33vw"/><div className="p-6"><p className="text-xs font-bold uppercase text-blue-200">{p.category}</p><h3 className="mt-3 text-xl font-extrabold">{p.title}</h3><p className="mt-2 text-sm text-slate-300">{p.location}</p></div></article>)}</div><Link href="/realisations" className="btn btn-primary mt-8">Voir les réalisations</Link></div></section>}
  <section className="section"><div className="site-container grid items-center gap-14 lg:grid-cols-2"><div><span className="eyebrow">Négoce & fournitures</span><h2 className="heading font-extrabold text-navy">Un appui d’approvisionnement pour vos besoins techniques.</h2><p className="lead mt-6">Matériels, équipements électriques, produits industriels et lubrifiants industriels et marins pour les besoins professionnels.</p>{["Lubrifiants industriels et marins","Équipements et matériels électriques","Import-export et coordination logistique"].map(x=><p key={x} className="mt-5 flex gap-3 font-bold"><Check className="text-brand"/>{x}</p>)}<Link href="/services/negoce-import-export" className="btn btn-primary mt-8">Découvrir cette expertise</Link></div><ImageLightbox src="https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1400&q=85" alt="Entrepôt de logistique et d’approvisionnement" className="h-[520px] rounded-lg shadow-soft" sizes="50vw"/></div></section>
  <section className="section bg-off"><div className="site-container grid overflow-hidden rounded-lg border bg-navy text-white lg:grid-cols-[.72fr_1.28fr]"><div className="p-8 lg:p-12"><span className="eyebrow !text-blue-300">Prise de contact</span><h2 className="text-3xl font-extrabold">Parlez-nous de votre projet.</h2><p className="mt-5 leading-7 text-slate-300">Présentez votre besoin. Notre équipe pourra vous répondre avec les premiers éléments utiles.</p></div><ContactForm /></div></section>
  </main>; }
